version: '3.1'

services:
  couch:
    image: couchdb    
    ports:
      - "5984:5984"
    volumes:
      - asiot:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
volumes:
  asiot:
